<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Multiple regression | Sports Data Analysis and Visualization</title>
  <meta name="description" content="This book is the companion to the University of Nebraska-Lincoln’s SPMC350 course in the College of Journalism and Mass Communications." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Multiple regression | Sports Data Analysis and Visualization" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book is the companion to the University of Nebraska-Lincoln’s SPMC350 course in the College of Journalism and Mass Communications." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Multiple regression | Sports Data Analysis and Visualization" />
  
  <meta name="twitter:description" content="This book is the companion to the University of Nebraska-Lincoln’s SPMC350 course in the College of Journalism and Mass Communications." />
  

<meta name="author" content="By Matt Waite" />


<meta name="date" content="2019-07-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correlations-and-regression.html"/>
<link rel="next" href="residuals.html"/>
<script src="libs/header-attrs-2.5/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-160712129-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-160712129-1');
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Sports Data Analysis and Visualization</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Throwing cold water on hot takes</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#requirements-and-conventions"><i class="fa fa-check"></i><b>1.1</b> Requirements and Conventions</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#about-this-book"><i class="fa fa-check"></i><b>1.2</b> About this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="the-very-basics.html"><a href="the-very-basics.html"><i class="fa fa-check"></i><b>2</b> The very basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-very-basics.html"><a href="the-very-basics.html#adding-libraries-part-1"><i class="fa fa-check"></i><b>2.1</b> Adding libraries, part 1</a></li>
<li class="chapter" data-level="2.2" data-path="the-very-basics.html"><a href="the-very-basics.html#adding-libraries-part-2"><i class="fa fa-check"></i><b>2.2</b> Adding libraries, part 2</a></li>
<li class="chapter" data-level="2.3" data-path="the-very-basics.html"><a href="the-very-basics.html#notebooks"><i class="fa fa-check"></i><b>2.3</b> Notebooks</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures-and-types.html"><a href="data-structures-and-types.html"><i class="fa fa-check"></i><b>3</b> Data, structures and types</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures-and-types.html"><a href="data-structures-and-types.html#rows-and-columns"><i class="fa fa-check"></i><b>3.1</b> Rows and columns</a></li>
<li class="chapter" data-level="3.2" data-path="data-structures-and-types.html"><a href="data-structures-and-types.html#types"><i class="fa fa-check"></i><b>3.2</b> Types</a></li>
<li class="chapter" data-level="3.3" data-path="data-structures-and-types.html"><a href="data-structures-and-types.html#a-simple-way-to-get-data"><i class="fa fa-check"></i><b>3.3</b> A simple way to get data</a></li>
<li class="chapter" data-level="3.4" data-path="data-structures-and-types.html"><a href="data-structures-and-types.html#cleaning-the-data"><i class="fa fa-check"></i><b>3.4</b> Cleaning the data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="aggregates.html"><a href="aggregates.html"><i class="fa fa-check"></i><b>4</b> Aggregates</a>
<ul>
<li class="chapter" data-level="4.1" data-path="aggregates.html"><a href="aggregates.html#basic-data-analysis-group-by-and-count"><i class="fa fa-check"></i><b>4.1</b> Basic data analysis: Group By and Count</a></li>
<li class="chapter" data-level="4.2" data-path="aggregates.html"><a href="aggregates.html#other-aggregates-mean-and-median"><i class="fa fa-check"></i><b>4.2</b> Other aggregates: Mean and median</a></li>
<li class="chapter" data-level="4.3" data-path="aggregates.html"><a href="aggregates.html#even-more-aggregates"><i class="fa fa-check"></i><b>4.3</b> Even more aggregates</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="mutating-data.html"><a href="mutating-data.html"><i class="fa fa-check"></i><b>5</b> Mutating data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="mutating-data.html"><a href="mutating-data.html#a-more-complex-example"><i class="fa fa-check"></i><b>5.1</b> A more complex example</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="filters-and-selections.html"><a href="filters-and-selections.html"><i class="fa fa-check"></i><b>6</b> Filters and selections</a>
<ul>
<li class="chapter" data-level="6.1" data-path="filters-and-selections.html"><a href="filters-and-selections.html#selecting-data-to-make-it-easier-to-read"><i class="fa fa-check"></i><b>6.1</b> Selecting data to make it easier to read</a></li>
<li class="chapter" data-level="6.2" data-path="filters-and-selections.html"><a href="filters-and-selections.html#using-conditional-filters-to-set-limits"><i class="fa fa-check"></i><b>6.2</b> Using conditional filters to set limits</a></li>
<li class="chapter" data-level="6.3" data-path="filters-and-selections.html"><a href="filters-and-selections.html#top-list"><i class="fa fa-check"></i><b>6.3</b> Top list</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="transforming-data.html"><a href="transforming-data.html"><i class="fa fa-check"></i><b>7</b> Transforming data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="transforming-data.html"><a href="transforming-data.html#making-long-data-wide"><i class="fa fa-check"></i><b>7.1</b> Making long data wide</a></li>
<li class="chapter" data-level="7.2" data-path="transforming-data.html"><a href="transforming-data.html#why-this-matters"><i class="fa fa-check"></i><b>7.2</b> Why this matters</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="significance-tests.html"><a href="significance-tests.html"><i class="fa fa-check"></i><b>8</b> Significance tests</a>
<ul>
<li class="chapter" data-level="8.1" data-path="significance-tests.html"><a href="significance-tests.html#accepting-the-null-hypothesis"><i class="fa fa-check"></i><b>8.1</b> Accepting the null hypothesis</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="correlations-and-regression.html"><a href="correlations-and-regression.html"><i class="fa fa-check"></i><b>9</b> Correlations and regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="correlations-and-regression.html"><a href="correlations-and-regression.html#a-more-predictive-example"><i class="fa fa-check"></i><b>9.1</b> A more predictive example</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>10</b> Multiple regression</a></li>
<li class="chapter" data-level="11" data-path="residuals.html"><a href="residuals.html"><i class="fa fa-check"></i><b>11</b> Residuals</a>
<ul>
<li class="chapter" data-level="11.1" data-path="residuals.html"><a href="residuals.html#penalties"><i class="fa fa-check"></i><b>11.1</b> Penalties</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="z-scores.html"><a href="z-scores.html"><i class="fa fa-check"></i><b>12</b> Z-scores</a>
<ul>
<li class="chapter" data-level="12.1" data-path="z-scores.html"><a href="z-scores.html#calculating-a-z-score-in-r"><i class="fa fa-check"></i><b>12.1</b> Calculating a Z score in R</a></li>
<li class="chapter" data-level="12.2" data-path="z-scores.html"><a href="z-scores.html#writing-about-z-scores"><i class="fa fa-check"></i><b>12.2</b> Writing about z-scores</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>13</b> Clustering</a>
<ul>
<li class="chapter" data-level="13.1" data-path="clustering.html"><a href="clustering.html#advanced-metrics"><i class="fa fa-check"></i><b>13.1</b> Advanced metrics</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="simulations.html"><a href="simulations.html"><i class="fa fa-check"></i><b>14</b> Simulations</a>
<ul>
<li class="chapter" data-level="14.1" data-path="simulations.html"><a href="simulations.html#cold-streaks"><i class="fa fa-check"></i><b>14.1</b> Cold streaks</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html"><i class="fa fa-check"></i><b>15</b> Intro to ggplot</a>
<ul>
<li class="chapter" data-level="15.1" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#the-bar-chart"><i class="fa fa-check"></i><b>15.1</b> The bar chart</a></li>
<li class="chapter" data-level="15.2" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#scales"><i class="fa fa-check"></i><b>15.2</b> Scales</a></li>
<li class="chapter" data-level="15.3" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#styling"><i class="fa fa-check"></i><b>15.3</b> Styling</a></li>
<li class="chapter" data-level="15.4" data-path="intro-to-ggplot.html"><a href="intro-to-ggplot.html#one-last-trick-coord-flip"><i class="fa fa-check"></i><b>15.4</b> One last trick: coord flip</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="stacked-bar-charts.html"><a href="stacked-bar-charts.html"><i class="fa fa-check"></i><b>16</b> Stacked bar charts</a></li>
<li class="chapter" data-level="17" data-path="circular-bar-plots.html"><a href="circular-bar-plots.html"><i class="fa fa-check"></i><b>17</b> Circular bar plots</a>
<ul>
<li class="chapter" data-level="17.1" data-path="circular-bar-plots.html"><a href="circular-bar-plots.html#does-november-basketball-matter"><i class="fa fa-check"></i><b>17.1</b> Does November basketball matter?</a></li>
<li class="chapter" data-level="17.2" data-path="circular-bar-plots.html"><a href="circular-bar-plots.html#does-it-show-you-where-you-are"><i class="fa fa-check"></i><b>17.2</b> Does it show you where you are?</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="waffle-charts.html"><a href="waffle-charts.html"><i class="fa fa-check"></i><b>18</b> Waffle charts</a>
<ul>
<li class="chapter" data-level="18.1" data-path="waffle-charts.html"><a href="waffle-charts.html#waffles-two-ways-part-1"><i class="fa fa-check"></i><b>18.1</b> Waffles two ways: Part 1</a></li>
<li class="chapter" data-level="18.2" data-path="waffle-charts.html"><a href="waffle-charts.html#waffles-two-ways-part-2"><i class="fa fa-check"></i><b>18.2</b> Waffles two ways: Part 2</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="line-charts.html"><a href="line-charts.html"><i class="fa fa-check"></i><b>19</b> Line charts</a>
<ul>
<li class="chapter" data-level="19.1" data-path="line-charts.html"><a href="line-charts.html#this-is-too-simple."><i class="fa fa-check"></i><b>19.1</b> This is too simple.</a></li>
<li class="chapter" data-level="19.2" data-path="line-charts.html"><a href="line-charts.html#but-what-if-i-wanted-to-add-a-lot-of-lines."><i class="fa fa-check"></i><b>19.2</b> But what if I wanted to add a lot of lines.</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="step-charts.html"><a href="step-charts.html"><i class="fa fa-check"></i><b>20</b> Step charts</a></li>
<li class="chapter" data-level="21" data-path="ridge-charts.html"><a href="ridge-charts.html"><i class="fa fa-check"></i><b>21</b> Ridge charts</a></li>
<li class="chapter" data-level="22" data-path="dumbbell-and-lollipop-charts.html"><a href="dumbbell-and-lollipop-charts.html"><i class="fa fa-check"></i><b>22</b> Dumbbell and lollipop charts</a>
<ul>
<li class="chapter" data-level="22.1" data-path="dumbbell-and-lollipop-charts.html"><a href="dumbbell-and-lollipop-charts.html#dumbbell-plots"><i class="fa fa-check"></i><b>22.1</b> Dumbbell plots</a></li>
<li class="chapter" data-level="22.2" data-path="dumbbell-and-lollipop-charts.html"><a href="dumbbell-and-lollipop-charts.html#lollipop-charts"><i class="fa fa-check"></i><b>22.2</b> Lollipop charts</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="scatterplots.html"><a href="scatterplots.html"><i class="fa fa-check"></i><b>23</b> Scatterplots</a></li>
<li class="chapter" data-level="24" data-path="bubble-charts.html"><a href="bubble-charts.html"><i class="fa fa-check"></i><b>24</b> Bubble charts</a></li>
<li class="chapter" data-level="25" data-path="beeswarm-plots.html"><a href="beeswarm-plots.html"><i class="fa fa-check"></i><b>25</b> Beeswarm plots</a>
<ul>
<li class="chapter" data-level="25.1" data-path="beeswarm-plots.html"><a href="beeswarm-plots.html#a-few-other-options"><i class="fa fa-check"></i><b>25.1</b> A few other options</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="bump-charts.html"><a href="bump-charts.html"><i class="fa fa-check"></i><b>26</b> Bump charts</a></li>
<li class="chapter" data-level="27" data-path="tables.html"><a href="tables.html"><i class="fa fa-check"></i><b>27</b> Tables</a>
<ul>
<li class="chapter" data-level="27.1" data-path="tables.html"><a href="tables.html#exporting-tables"><i class="fa fa-check"></i><b>27.1</b> Exporting tables</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="facet-wraps.html"><a href="facet-wraps.html"><i class="fa fa-check"></i><b>28</b> Facet wraps</a>
<ul>
<li class="chapter" data-level="28.1" data-path="facet-wraps.html"><a href="facet-wraps.html#facet-grid-vs-facet-wraps"><i class="fa fa-check"></i><b>28.1</b> Facet grid vs facet wraps</a></li>
<li class="chapter" data-level="28.2" data-path="facet-wraps.html"><a href="facet-wraps.html#other-types"><i class="fa fa-check"></i><b>28.2</b> Other types</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="arranging-multiple-plots-together.html"><a href="arranging-multiple-plots-together.html"><i class="fa fa-check"></i><b>29</b> Arranging multiple plots together</a></li>
<li class="chapter" data-level="30" data-path="encircling-points-on-a-scatterplot.html"><a href="encircling-points-on-a-scatterplot.html"><i class="fa fa-check"></i><b>30</b> Encircling points on a scatterplot</a>
<ul>
<li class="chapter" data-level="30.1" data-path="encircling-points-on-a-scatterplot.html"><a href="encircling-points-on-a-scatterplot.html#a-different-more-local-example"><i class="fa fa-check"></i><b>30.1</b> A different, more local example</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="plotly.html"><a href="plotly.html"><i class="fa fa-check"></i><b>31</b> Plotly</a>
<ul>
<li class="chapter" data-level="31.1" data-path="plotly.html"><a href="plotly.html#publishing-using-plotly"><i class="fa fa-check"></i><b>31.1</b> Publishing using Plotly</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="text-cleaning.html"><a href="text-cleaning.html"><i class="fa fa-check"></i><b>32</b> Text cleaning</a>
<ul>
<li class="chapter" data-level="32.1" data-path="text-cleaning.html"><a href="text-cleaning.html#stripping-out-text"><i class="fa fa-check"></i><b>32.1</b> Stripping out text</a></li>
<li class="chapter" data-level="32.2" data-path="text-cleaning.html"><a href="text-cleaning.html#another-example-splitting-columns"><i class="fa fa-check"></i><b>32.2</b> Another example: splitting columns</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="headlines.html"><a href="headlines.html"><i class="fa fa-check"></i><b>33</b> Headlines</a></li>
<li class="chapter" data-level="34" data-path="annotations.html"><a href="annotations.html"><i class="fa fa-check"></i><b>34</b> Annotations</a></li>
<li class="chapter" data-level="35" data-path="finishing-touches.html"><a href="finishing-touches.html"><i class="fa fa-check"></i><b>35</b> Finishing touches</a>
<ul>
<li class="chapter" data-level="35.1" data-path="finishing-touches.html"><a href="finishing-touches.html#graphics-vs-visual-stories"><i class="fa fa-check"></i><b>35.1</b> Graphics vs visual stories</a></li>
<li class="chapter" data-level="35.2" data-path="finishing-touches.html"><a href="finishing-touches.html#getting-ggplot-closer-to-output"><i class="fa fa-check"></i><b>35.2</b> Getting ggplot closer to output</a></li>
<li class="chapter" data-level="35.3" data-path="finishing-touches.html"><a href="finishing-touches.html#waffle-charts-require-special-attention"><i class="fa fa-check"></i><b>35.3</b> Waffle charts require special attention</a></li>
</ul></li>
<li class="chapter" data-level="36" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html"><i class="fa fa-check"></i><b>36</b> Rtweet and Text Analysis</a>
<ul>
<li class="chapter" data-level="36.1" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#prerequisites"><i class="fa fa-check"></i><b>36.1</b> Prerequisites</a>
<ul>
<li class="chapter" data-level="36.1.1" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#tools-for-text-analysis"><i class="fa fa-check"></i><b>36.1.1</b> Tools for text analysis</a></li>
<li class="chapter" data-level="36.1.2" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#working-with-string-data"><i class="fa fa-check"></i><b>36.1.2</b> Working with string data</a></li>
</ul></li>
<li class="chapter" data-level="36.2" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#verifying-your-account-to-access-twitter-data"><i class="fa fa-check"></i><b>36.2</b> Verifying your account to access Twitter data</a></li>
<li class="chapter" data-level="36.3" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#the-data-used-here"><i class="fa fa-check"></i><b>36.3</b> The data used here</a></li>
<li class="chapter" data-level="36.4" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#data-exploration"><i class="fa fa-check"></i><b>36.4</b> Data Exploration</a></li>
<li class="chapter" data-level="36.5" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#cleaning-data-for-analysis"><i class="fa fa-check"></i><b>36.5</b> Cleaning data for analysis</a>
<ul>
<li class="chapter" data-level="36.5.1" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#fixing-the-date-and-focusing-only-on-game-tweets"><i class="fa fa-check"></i><b>36.5.1</b> Fixing the date and focusing only on game tweets</a></li>
</ul></li>
<li class="chapter" data-level="36.6" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#number-of-tweets-throughout-the-game"><i class="fa fa-check"></i><b>36.6</b> Number of tweets throughout the game</a></li>
<li class="chapter" data-level="36.7" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#tidying-the-text-data-for-analysis-applying-the-sentiment-scores"><i class="fa fa-check"></i><b>36.7</b> Tidying the text data for analysis, applying the sentiment scores</a>
<ul>
<li class="chapter" data-level="36.7.1" data-path="rtweet-and-text-analysis.html"><a href="rtweet-and-text-analysis.html#example-2---nebraskas-loss-to-purdue-what-were-fans-sentiments-towards-this-loss"><i class="fa fa-check"></i><b>36.7.1</b> Example 2 - Nebraska’s loss to Purdue, what were fan’s sentiments towards this loss?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="37" data-path="intro-to-rvest.html"><a href="intro-to-rvest.html"><i class="fa fa-check"></i><b>37</b> Intro to rvest</a>
<ul>
<li class="chapter" data-level="37.1" data-path="intro-to-rvest.html"><a href="intro-to-rvest.html#a-slightly-more-complicated-example"><i class="fa fa-check"></i><b>37.1</b> A slightly more complicated example</a></li>
<li class="chapter" data-level="37.2" data-path="intro-to-rvest.html"><a href="intro-to-rvest.html#an-even-more-complicated-example"><i class="fa fa-check"></i><b>37.2</b> An even more complicated example</a></li>
</ul></li>
<li class="chapter" data-level="38" data-path="advanced-rvest.html"><a href="advanced-rvest.html"><i class="fa fa-check"></i><b>38</b> Advanced rvest</a>
<ul>
<li class="chapter" data-level="38.1" data-path="advanced-rvest.html"><a href="advanced-rvest.html#one-last-bit"><i class="fa fa-check"></i><b>38.1</b> One last bit</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="building-your-own-blog-with-blogdown.html"><a href="building-your-own-blog-with-blogdown.html"><i class="fa fa-check"></i><b>39</b> Building your own blog with blogdown</a>
<ul>
<li class="chapter" data-level="39.1" data-path="building-your-own-blog-with-blogdown.html"><a href="building-your-own-blog-with-blogdown.html#setup"><i class="fa fa-check"></i><b>39.1</b> Setup</a></li>
<li class="chapter" data-level="39.2" data-path="building-your-own-blog-with-blogdown.html"><a href="building-your-own-blog-with-blogdown.html#editing-existing-markdown-content"><i class="fa fa-check"></i><b>39.2</b> Editing existing Markdown content</a></li>
<li class="chapter" data-level="39.3" data-path="building-your-own-blog-with-blogdown.html"><a href="building-your-own-blog-with-blogdown.html#creating-a-new-post-in-r-markdown"><i class="fa fa-check"></i><b>39.3</b> Creating a new post in R Markdown</a></li>
<li class="chapter" data-level="39.4" data-path="building-your-own-blog-with-blogdown.html"><a href="building-your-own-blog-with-blogdown.html#publishing-your-site"><i class="fa fa-check"></i><b>39.4</b> Publishing your site</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="assignments.html"><a href="assignments.html"><i class="fa fa-check"></i><b>40</b> Assignments</a></li>
<li class="chapter" data-level="41" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>41</b> Appendix</a>
<ul>
<li class="chapter" data-level="41.1" data-path="appendix.html"><a href="appendix.html#how-to-get-help-in-this-class"><i class="fa fa-check"></i><b>41.1</b> How to get help in this class</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Sports Data Analysis and Visualization</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-regression" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> Multiple regression</h1>
<p>Last chapter, we looked at correlations and linear regression to predict how one element of a game would predict the score. But we know that a single variable, in all but the rarest instances, is not going to be that predictive. We need more than one. Enter multiple regression. Multiple regression lets us add – wait for it – multiple predictors to our equation to help us get a better fit to reality.</p>
<p>That presents it’s own problems. So let’s get set up. The dataset we’ll use is all college football games since the 2011 season.</p>
<pre><p><strong>For this walkthrough:</strong></p><p><a href="http://mattwaite.github.io/sportsdatafiles/footballlogs1120.csv">
  <button class="btn btn-danger"><i class="fa fa-save"></i> Download csv file</button>
</a></p></pre>
<p>We need the tidyverse.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="multiple-regression.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>And the data.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="multiple-regression.html#cb115-1" aria-hidden="true" tabindex="-1"></a>logs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/footballlogs1120.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   .default = col_double(),
##   Date = col_date(format = &quot;&quot;),
##   HomeAway = col_character(),
##   Opponent = col_character(),
##   Result = col_character(),
##   TeamFull = col_character(),
##   TeamURL = col_character(),
##   Outcome = col_character(),
##   Team = col_character(),
##   Conference = col_character()
## )
## ℹ Use `spec()` for the full column specifications.</code></pre>
<p>One way to show how successful a footballl team was for a game is to show the differential between the team’s score and the opponent’s score. Score a lot more than the opponent = good, score a lot less than the opponent = bad. And, relatively speaking, the more the better. So let’s create that differential. Let’s also get our net yardage stat back. And because we’ll need it later, let’s add the turnover margin.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="multiple-regression.html#cb117-1" aria-hidden="true" tabindex="-1"></a>logs <span class="ot">&lt;-</span> logs <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb117-2"><a href="multiple-regression.html#cb117-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Differential =</span> TeamScore <span class="sc">-</span> OpponentScore, </span>
<span id="cb117-3"><a href="multiple-regression.html#cb117-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">NetYards =</span> OffensiveYards <span class="sc">-</span> DefYards, </span>
<span id="cb117-4"><a href="multiple-regression.html#cb117-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">TurnoverMargin =</span> DefTotalTurnovers <span class="sc">-</span> TotalTurnovers)</span></code></pre></div>
<p>The linear model code we used before is pretty straight forward. Its <code>field</code> is predicted by <code>field</code>. Here’s a simple linear model that looks at predicting a team’s point differential by looking at their net yards.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="multiple-regression.html#cb118-1" aria-hidden="true" tabindex="-1"></a>yards <span class="ot">&lt;-</span> <span class="fu">lm</span>(Differential <span class="sc">~</span> NetYards, <span class="at">data=</span>logs)</span>
<span id="cb118-2"><a href="multiple-regression.html#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(yards)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Differential ~ NetYards, data = logs)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -52.052  -8.736  -0.004   8.753  64.486 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.4918375  0.1052811   4.672 3.01e-06 ***
## NetYards    0.1046592  0.0005882 177.920  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.12 on 15605 degrees of freedom
## Multiple R-squared:  0.6698, Adjusted R-squared:  0.6698 
## F-statistic: 3.166e+04 on 1 and 15605 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Remember: There’s a lot here, but only some of it we care about. What is the Adjusted R-squared value? What’s the p-value and is it less than .05? In this case, we can predict 67 percent of the difference in differential with the net yardage in the game.</p>
<p>To add more predictors to this mix, we merely add them. But it’s not that simple, as you’ll see in a moment. So first, let’s look at adding how well the other team shot to our prediction model:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="multiple-regression.html#cb120-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Differential <span class="sc">~</span> NetYards <span class="sc">+</span> TurnoverMargin, <span class="at">data=</span>logs)</span>
<span id="cb120-2"><a href="multiple-regression.html#cb120-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Differential ~ NetYards + TurnoverMargin, data = logs)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -39.031  -6.983  -0.025   6.932  40.789 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    0.4608403  0.0846844   5.442 5.35e-08 ***
## NetYards       0.0966321  0.0004811 200.864  &lt; 2e-16 ***
## TurnoverMargin 4.1968337  0.0454801  92.278  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 10.55 on 15604 degrees of freedom
## Multiple R-squared:  0.7864, Adjusted R-squared:  0.7864 
## F-statistic: 2.872e+04 on 2 and 15604 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>First things first: What is the adjusted R-squared?</p>
<p>Second: what is the p-value and is it less than .05?</p>
<p>Third: Compare the residual standard error. We went from 13.12 to 10.55. The meaning of this is both really opaque and also simple – by adding data, we reduced the amount of error in our model. Residual standard error is the total distance between what our model would predict and what we actually have in the data. So lots of residual error means the distance between reality and our model is wider. So the width of our predictive range in this example shrank while we improved the amount of the difference we could predict. That’s good, and not always going to be the case.</p>
<p>One of the more difficult things to understand about multiple regression is the issue of multicollinearity. What that means is that there is significant correlation overlap between two variables – the two are related to each other as well as to the target output – and all you are doing by adding both of them is adding error with no real value to the R-squared. In pure statistics, we don’t want any multicollinearity at all. Violating that assumption limits the applicability of what you are doing. So if we have some multicollinearity, it limits our scope of application to college football We can’t say this will work for every football league and level everywhere. What we need to do is see how correlated each value is to each other and throw out ones that are highly co-correlated.</p>
<p>So to find those, we have to create a correlation matrix that shows us how each value is correlated to our outcome variable, but also with each other. We can do that in the <code>Hmisc</code> library. We install that in the console with <code>install.packages("Hmisc")</code></p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="multiple-regression.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span></code></pre></div>
<p>We can pass in every numeric value to the Hmisc library and get a correlation matrix out of it, but since we have a large number of values – and many of them character values – we should strip that down and reorder them. So that’s what I’m doing here. I’m saying give me differential first, and then columns 9-24, and then 26-41. Why the skip? There’s a blank column in the middle of the data – a remnant of the scraper I used.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="multiple-regression.html#cb123-1" aria-hidden="true" tabindex="-1"></a>simplelogs <span class="ot">&lt;-</span> logs <span class="sc">%&gt;%</span> <span class="fu">select_if</span>(is.numeric) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>Game) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Differential, NetYards, TurnoverMargin, <span class="fu">everything</span>())</span></code></pre></div>
<p>Before we proceed, what we’re looking to do is follow the Differential column down, looking for correlation values near 1 or -1. Correlations go from -1, meaning perfect negative correlation, to 0, meaning no correlation, to 1, meaning perfect positive correlation. So we’re looking for numbers near 1 or -1 for their predictive value. BUT: We then need to see if that value is also highly correlated with something else. If it is, we have a decision to make.</p>
<p>We get our correlation matrix like this:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="multiple-regression.html#cb124-1" aria-hidden="true" tabindex="-1"></a>cormatrix <span class="ot">&lt;-</span> <span class="fu">rcorr</span>(<span class="fu">as.matrix</span>(simplelogs))</span>
<span id="cb124-2"><a href="multiple-regression.html#cb124-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-3"><a href="multiple-regression.html#cb124-3" aria-hidden="true" tabindex="-1"></a>cormatrix<span class="sc">$</span>r</span></code></pre></div>
<pre><code>##                   Differential      NetYards TurnoverMargin  PassingCmp
## Differential        1.00000000  8.184193e-01   0.4837849198  0.03118170
## NetYards            0.81841934  1.000000e+00   0.1808173764  0.19290045
## TurnoverMargin      0.48378492  1.808174e-01   1.0000000000 -0.09233553
## PassingCmp          0.03118170  1.929004e-01  -0.0923355289  1.00000000
## PassingAtt         -0.19686950 -7.097271e-03  -0.1939446793  0.88589623
## PassingPct          0.42410345  4.230815e-01   0.1567432526  0.50717498
## PassingYds          0.22322068  3.660003e-01  -0.0255596419  0.80654722
## PassingTD           0.41571492  3.776967e-01   0.1458497043  0.42231692
## RushingAtt          0.36621257  4.169451e-01   0.1942339975 -0.36911655
## RushingYds          0.52945141  5.517793e-01   0.1959559925 -0.32669337
## RushingAvg          0.49317675  4.892094e-01   0.1512425735 -0.19464168
## RushingTD           0.57578332  4.734649e-01   0.2627916039 -0.13305246
## OffensivePlays      0.14922605  3.856779e-01  -0.0098582568  0.53304628
## OffensiveYards      0.58963784  7.222939e-01   0.1308007817  0.39936463
## OffenseAvg          0.61303088  6.273595e-01   0.1640078840  0.15135101
## FirstDownPass       0.17742548  3.296124e-01  -0.0519043178  0.85823184
## FirstDownRush       0.46104465  5.138962e-01   0.1438888221 -0.24594648
## FirstDownPen       -0.00567194 -1.419963e-02  -0.0212171554  0.15771675
## FirstDownTotal      0.46569860  6.160784e-01   0.0606678892  0.48947643
## Penalties          -0.01446172  6.431274e-02   0.0245826177  0.13394910
## PenaltyYds          0.01760113  9.250198e-02   0.0375348365  0.12542719
## Fumbles            -0.14420105 -9.215913e-05  -0.4544647395  0.01753247
## Interceptions      -0.34740859 -1.828408e-01  -0.5658983150  0.09952907
## TotalTurnovers     -0.35226029 -1.357271e-01  -0.7176732980  0.08533780
## TeamScore           0.78106738  6.372500e-01   0.3770822640  0.18334268
## OpponentScore      -0.76964262 -6.319258e-01  -0.3731455129  0.13856056
## DefPassingCmp      -0.06473817 -2.227403e-01   0.0828218918  0.08346001
## DefPassingAtt       0.15048839 -3.476179e-02   0.1819010221  0.07599800
## DefPassingPct      -0.42046253 -4.221770e-01  -0.1547820852  0.03694525
## DefPassingYds      -0.25733994 -3.976691e-01   0.0170156333  0.12715093
## DefPassingTD       -0.41930782 -3.805155e-01  -0.1479955551  0.11207117
## DefRushingAtt      -0.36480427 -4.156720e-01  -0.1927488957 -0.03564161
## DefRushingYds      -0.52342461 -5.478198e-01  -0.1942127993  0.01864717
## DefRushingAvg      -0.48630318 -4.871370e-01  -0.1469244778  0.04905028
## DefRushingTD       -0.56152960 -4.645077e-01  -0.2584394301  0.06194592
## DefPlays           -0.19091439 -4.210217e-01   0.0001525553  0.04182614
## DefYards           -0.59891323 -7.299795e-01  -0.1317978120  0.11616839
## DefAvg             -0.61875849 -6.395677e-01  -0.1615742932  0.10878889
## DefFirstDownPass   -0.21709433 -3.658307e-01   0.0425861829  0.09123305
## DefFirstDownRush   -0.45863262 -5.137995e-01  -0.1442285028 -0.01962705
## DefFirstDownPen    -0.02107814 -9.546899e-03   0.0146372877  0.05162783
## DefFirstDownTotal  -0.48687095 -6.329252e-01  -0.0664607512  0.06425565
## DefPenalties        0.01317935 -6.452130e-02  -0.0302781991  0.09772103
## DefPenaltyYds      -0.02890210 -1.011338e-01  -0.0461923015  0.10806661
## DefFumbles          0.15069928  1.689405e-03   0.4611567538 -0.04092384
## DefInterceptions    0.33233883  1.665064e-01   0.5702003054 -0.02870947
## DefTotalTurnovers   0.34523008  1.250021e-01   0.7239648943 -0.04795582
## Season             -0.00363621 -1.569119e-03  -0.0028876028 -0.03091173
##                     PassingAtt  PassingPct   PassingYds    PassingTD
## Differential      -0.196869502  0.42410345  0.223220680  0.415714923
## NetYards          -0.007097271  0.42308150  0.366000270  0.377696725
## TurnoverMargin    -0.193944679  0.15674325 -0.025559642  0.145849704
## PassingCmp         0.885896233  0.50717498  0.806547223  0.422316922
## PassingAtt         1.000000000  0.09315536  0.687271795  0.272813521
## PassingPct         0.093155364  1.00000000  0.474576058  0.394989670
## PassingYds         0.687271795  0.47457606  1.000000000  0.628178519
## PassingTD          0.272813521  0.39498967  0.628178519  1.000000000
## RushingAtt        -0.467518367  0.03613210 -0.263107487 -0.059376574
## RushingYds        -0.449975567  0.10449207 -0.200609277  0.066350138
## RushingAvg        -0.303577976  0.13444998 -0.082888644  0.150499189
## RushingTD         -0.292374841  0.24175736  0.011342402 -0.029015586
## OffensivePlays     0.553796697  0.12658649  0.435433701  0.215293539
## OffensiveYards     0.207675438  0.46417599  0.653171610  0.558994355
## OffenseAvg        -0.083538631  0.47899455  0.504666780  0.524444297
## FirstDownPass      0.746157690  0.47052335  0.883657791  0.521551760
## FirstDownRush     -0.367019503  0.12282841 -0.161359790  0.067439565
## FirstDownPen       0.197351786 -0.01284499  0.129006081  0.102871859
## FirstDownTotal     0.327399378  0.43330605  0.563311167  0.456860192
## Penalties          0.141768049  0.03463586  0.151550273  0.082259734
## PenaltyYds         0.119567124  0.05599523  0.151131721  0.100160624
## Fumbles            0.027478866 -0.01783733  0.008811146 -0.048018859
## Interceptions      0.254940410 -0.23627286  0.017618719 -0.114458545
## TotalTurnovers     0.207169253 -0.18699980  0.018846333 -0.116391065
## TeamScore         -0.035933316  0.44835810  0.431051906  0.618539629
## OpponentScore      0.272001348 -0.20669709  0.090668157 -0.019512592
## DefPassingCmp      0.083570904  0.02206021  0.126357936  0.091773507
## DefPassingAtt      0.057944813  0.05692377  0.145063141  0.144169653
## DefPassingPct      0.077374243 -0.07337905 -0.002052903 -0.081413409
## DefPassingYds      0.156497317 -0.02196601  0.155256065  0.075376864
## DefPassingTD       0.171067592 -0.08316878  0.097982769  0.035053345
## DefRushingAtt      0.083993629 -0.21380037 -0.037088960 -0.051053515
## DefRushingYds      0.119747148 -0.17947974 -0.010300250 -0.071383520
## DefRushingAvg      0.114462808 -0.11505322  0.008649510 -0.065672712
## DefRushingTD       0.155716440 -0.15511709  0.028151375 -0.033926688
## DefPlays           0.135316859 -0.14277058  0.108624632  0.094751037
## DefYards           0.215484942 -0.15211246  0.117075612  0.007116432
## DefAvg             0.175755717 -0.10704691  0.066058087 -0.058840155
## DefFirstDownPass   0.109208886 -0.01119101  0.123142671  0.065395375
## DefFirstDownRush   0.062313958 -0.15434159 -0.034360788 -0.068080474
## DefFirstDownPen    0.049336590  0.02691594  0.078576992  0.072627007
## DefFirstDownTotal  0.134090419 -0.11025611  0.083106670  0.016190934
## DefPenalties       0.144271935 -0.04301213  0.092139354  0.087539127
## DefPenaltyYds      0.162654164 -0.05390508  0.091809187  0.087458617
## DefFumbles        -0.035268306 -0.01779875 -0.037573349  0.043415306
## DefInterceptions  -0.067393814  0.06886121  0.008612120  0.088384660
## DefTotalTurnovers -0.073067543  0.03967676 -0.018006148  0.093981546
## Season            -0.042815333  0.01153492 -0.006117554  0.007749168
##                     RushingAtt   RushingYds   RushingAvg    RushingTD
## Differential       0.366212575  0.529451415  0.493176753  0.575783321
## NetYards           0.416945120  0.551779347  0.489209446  0.473464850
## TurnoverMargin     0.194233997  0.195955992  0.151242574  0.262791604
## PassingCmp        -0.369116550 -0.326693369 -0.194641684 -0.133052460
## PassingAtt        -0.467518367 -0.449975567 -0.303577976 -0.292374841
## PassingPct         0.036132096  0.104492066  0.134449978  0.241757360
## PassingYds        -0.263107487 -0.200609277 -0.082888644  0.011342402
## PassingTD         -0.059376574  0.066350138  0.150499189 -0.029015586
## RushingAtt         1.000000000  0.736583943  0.364284984  0.490658949
## RushingYds         0.736583943  1.000000000  0.871565174  0.695903189
## RushingAvg         0.364284984  0.871565174  1.000000000  0.607637826
## RushingTD          0.490658949  0.695903189  0.607637826  1.000000000
## OffensivePlays     0.477140312  0.246460859  0.041324341  0.171497768
## OffensiveYards     0.356671646  0.610784556  0.606659400  0.547046394
## OffenseAvg         0.138425296  0.576907524  0.708081627  0.545667695
## FirstDownPass     -0.235040292 -0.195601164 -0.092469432 -0.002819467
## FirstDownRush      0.788796974  0.868884675  0.659404370  0.595246572
## FirstDownPen      -0.003204555 -0.066910301 -0.080759132 -0.001136082
## FirstDownTotal     0.404815319  0.474808460  0.392505703  0.432561158
## Penalties         -0.024921198 -0.003651045  0.017975757 -0.025539221
## PenaltyYds        -0.002199279  0.033168959  0.054284078  0.009108827
## Fumbles            0.025578601 -0.028118399 -0.058261942 -0.058709124
## Interceptions     -0.193975079 -0.216449107 -0.172564128 -0.233234180
## TotalTurnovers    -0.127168356 -0.179027989 -0.166216652 -0.211526460
## TeamScore          0.343571991  0.571429522  0.560340983  0.698724429
## OpponentScore     -0.223024981 -0.246049036 -0.200498698 -0.188554772
## DefPassingCmp     -0.044763075  0.002351343  0.033307036  0.043038468
## DefPassingAtt      0.073608528  0.098937001  0.093487708  0.130716692
## DefPassingPct     -0.216287969 -0.180720848 -0.115717537 -0.152791861
## DefPassingYds     -0.050233964 -0.030415762 -0.010078082  0.005118324
## DefPassingTD      -0.059010431 -0.078502621 -0.070786506 -0.044702528
## DefRushingAtt     -0.410216642 -0.276569387 -0.117694938 -0.196242310
## DefRushingYds     -0.279183263 -0.225077345 -0.131739440 -0.196349300
## DefRushingAvg     -0.121621052 -0.134136582 -0.108134174 -0.151165356
## DefRushingTD      -0.194448775 -0.192176011 -0.145311374 -0.156635569
## DefPlays          -0.309019722 -0.159689121 -0.017255978 -0.053600005
## DefYards          -0.249498265 -0.193040997 -0.106779574 -0.142960915
## DefAvg            -0.119690358 -0.146487656 -0.127188735 -0.152049693
## DefFirstDownPass  -0.090092408 -0.047490894 -0.008586427 -0.007229665
## DefFirstDownRush  -0.317355086 -0.220166727 -0.100294586 -0.173767081
## DefFirstDownPen   -0.047381988 -0.006469058  0.026743015  0.011628275
## DefFirstDownTotal -0.301942200 -0.194065174 -0.073946954 -0.126211617
## DefPenalties      -0.044234601 -0.066155832 -0.057171981  0.001478081
## DefPenaltyYds     -0.060368138 -0.088133097 -0.076423381 -0.023191416
## DefFumbles         0.071037391  0.023590761 -0.006904102  0.081934337
## DefInterceptions   0.143215339  0.118930804  0.076394767  0.153598788
## DefTotalTurnovers  0.152731898  0.103830416  0.052362318  0.167539382
## Season            -0.006470762  0.015090607  0.029310251  0.010761615
##                   OffensivePlays OffensiveYards  OffenseAvg FirstDownPass
## Differential        0.1492260492    0.589637838  0.61303088   0.177425485
## NetYards            0.3856779392    0.722293918  0.62735954   0.329612380
## TurnoverMargin     -0.0098582568    0.130800782  0.16400788  -0.051904318
## PassingCmp          0.5330462787    0.399364632  0.15135101   0.858231839
## PassingAtt          0.5537966967    0.207675438 -0.08353863   0.746157690
## PassingPct          0.1265864872    0.464175994  0.47899455   0.470523352
## PassingYds          0.4354337011    0.653171610  0.50466678   0.883657791
## PassingTD           0.2152935388    0.558994355  0.52444430   0.521551760
## RushingAtt          0.4771403121    0.356671646  0.13842530  -0.235040292
## RushingYds          0.2464608593    0.610784556  0.57690752  -0.195601164
## RushingAvg          0.0413243412    0.606659400  0.70808163  -0.092469432
## RushingTD           0.1714977683    0.547046394  0.54566769  -0.002819467
## OffensivePlays      1.0000000000    0.542424397  0.04733582   0.520413497
## OffensiveYards      0.5424243966    1.000000000  0.85379007   0.563011577
## OffenseAvg          0.0473358159    0.853790068  1.00000000   0.350092632
## FirstDownPass       0.5204134972    0.563011577  0.35009263   1.000000000
## FirstDownRush       0.3781141523    0.541165081  0.41380414  -0.176035283
## FirstDownPen        0.1931821714    0.052549729 -0.04818553   0.127923002
## FirstDownTotal      0.7067980430    0.822273393  0.54765028   0.632578575
## Penalties           0.1174670579    0.119665050  0.06686068   0.095769976
## PenaltyYds          0.1167981247    0.147785771  0.10159079   0.096191798
## Fumbles             0.0514118771   -0.014611934 -0.04910112  -0.002669702
## Interceptions       0.0707420861   -0.153058437 -0.22086304   0.047918056
## TotalTurnovers      0.0861769432   -0.123142627 -0.19605167   0.033805622
## TeamScore           0.2878976199    0.790058468  0.76105515   0.348506805
## OpponentScore       0.0603404859   -0.116896356 -0.18323754   0.078087301
## DefPassingCmp       0.0409196811    0.103943303  0.09421622   0.091467148
## DefPassingAtt       0.1269410280    0.193714572  0.15018634   0.099017964
## DefPassingPct      -0.1268359214   -0.141363954 -0.09631045   0.008201755
## DefPassingYds       0.1082675145    0.101973122  0.04818640   0.125262682
## DefPassingTD        0.1144859698    0.018515887 -0.05340694   0.090586531
## DefRushingAtt      -0.3028923478   -0.243742972 -0.10829113  -0.078858613
## DefRushingYds      -0.1439228873   -0.182292260 -0.13449228  -0.026930969
## DefRushingAvg      -0.0007670721   -0.096687847 -0.11851074   0.011869282
## DefRushingTD       -0.0283493049   -0.125784441 -0.13842291   0.018320394
## DefPlays           -0.1565479001   -0.035633936  0.04743620   0.024332221
## DefYards           -0.0207822877   -0.054582037 -0.06201003   0.080510479
## DefAvg              0.0619862494   -0.059835995 -0.11515218   0.073494860
## DefFirstDownPass    0.0237109843    0.062820458  0.05355860   0.094812163
## DefFirstDownRush   -0.2369763215   -0.197943110 -0.09623351  -0.048360863
## DefFirstDownPen     0.0044182172    0.058507968  0.06481826   0.059488255
## DefFirstDownTotal  -0.1511006437   -0.082828263 -0.01566227   0.043655644
## DefPenalties        0.1017644325    0.023336190 -0.02925259   0.074673629
## DefPenaltyYds       0.1048427505    0.006082620 -0.05169993   0.076942358
## DefFumbles          0.0318497808   -0.012133968 -0.02853415  -0.048511328
## DefInterceptions    0.0678983530    0.098884830  0.08018058  -0.012722149
## DefTotalTurnovers   0.0712216676    0.065699798  0.04112451  -0.040989258
## Season             -0.0486606092    0.006719496  0.03847022  -0.021594636
##                   FirstDownRush  FirstDownPen FirstDownTotal    Penalties
## Differential       0.4610446515 -0.0056719400    0.465698595 -0.014461721
## NetYards           0.5138962499 -0.0141996290    0.616078422  0.064312738
## TurnoverMargin     0.1438888221 -0.0212171554    0.060667889  0.024582618
## PassingCmp        -0.2459464797  0.1577167545    0.489476431  0.133949104
## PassingAtt        -0.3670195030  0.1973517860    0.327399378  0.141768049
## PassingPct         0.1228284090 -0.0128449897    0.433306049  0.034635855
## PassingYds        -0.1613597905  0.1290060812    0.563311167  0.151550273
## PassingTD          0.0674395650  0.1028718590    0.456860192  0.082259734
## RushingAtt         0.7887969735 -0.0032045552    0.404815319 -0.024921198
## RushingYds         0.8688846753 -0.0669103014    0.474808460 -0.003651045
## RushingAvg         0.6594043700 -0.0807591323    0.392505703  0.017975757
## RushingTD          0.5952465724 -0.0011360821    0.432561158 -0.025539221
## OffensivePlays     0.3781141523  0.1931821714    0.706798043  0.117467058
## OffensiveYards     0.5411650814  0.0525497292    0.822273393  0.119665050
## OffenseAvg         0.4138041377 -0.0481855308    0.547650277  0.066860679
## FirstDownPass     -0.1760352833  0.1279230020    0.632578575  0.095769976
## FirstDownRush      1.0000000000 -0.0640698685    0.578677075 -0.036810209
## FirstDownPen      -0.0640698685  1.0000000000    0.271006893  0.131796886
## FirstDownTotal     0.5786770748  0.2710068926    1.000000000  0.073197638
## Penalties         -0.0368102087  0.1317968858    0.073197638  1.000000000
## PenaltyYds        -0.0038110643  0.1331976516    0.098139564  0.903246349
## Fumbles           -0.0127589089 -0.0001733341   -0.010522510 -0.005346654
## Interceptions     -0.1823861332  0.0214575248   -0.091526136  0.027625989
## TotalTurnovers    -0.1436894309  0.0158077753   -0.074806518  0.016995007
## TeamScore          0.4922799315  0.0696961188    0.632897568  0.045390014
## OpponentScore     -0.2196973570  0.0801568972   -0.083219329  0.069089389
## DefPassingCmp     -0.0351952073  0.0550827638    0.054621111  0.102064433
## DefPassingAtt      0.0425376517  0.0504467878    0.115086837  0.148129510
## DefPassingPct     -0.1563389121  0.0361246166   -0.098512229 -0.036848531
## DefPassingYds     -0.0530266913  0.0854845045    0.073302813  0.096286575
## DefPassingTD      -0.0724142119  0.0819003858    0.033416927  0.089942486
## DefRushingAtt     -0.3153770802 -0.0437639450   -0.299959508 -0.045386998
## DefRushingYds     -0.2196474882  0.0049716253   -0.181281160 -0.069403770
## DefRushingAvg     -0.1024397880  0.0402209526   -0.059266250 -0.059746435
## DefRushingTD      -0.1691695555  0.0296305740   -0.103644138  0.001729374
## DefPlays          -0.2514420854  0.0090586645   -0.165515581  0.103930020
## DefYards          -0.2071478834  0.0724343129   -0.076869161  0.025406067
## DefAvg            -0.1077475877  0.0813642808   -0.006762158 -0.026690341
## DefFirstDownPass  -0.0684673287  0.0650428178    0.030148892  0.078466818
## DefFirstDownRush  -0.2246581052 -0.0164089821   -0.213167195 -0.080014867
## DefFirstDownPen   -0.0271049617  0.0709464960    0.034896710  0.544815636
## DefFirstDownTotal -0.2243526184  0.0464600265   -0.123036459  0.124940137
## DefPenalties      -0.0775132732  0.5421750750    0.124255326  0.190344623
## DefPenaltyYds     -0.0976956398  0.6585481016    0.137953942  0.193217609
## DefFumbles         0.0007492654 -0.0219681886   -0.039437448  0.017507901
## DefInterceptions   0.0855201980 -0.0006859365    0.051837528  0.054737340
## DefTotalTurnovers  0.0641260141 -0.0147851433    0.012948409  0.052108799
## Season             0.0087181647  0.0662421947    0.003573008  0.029358706
##                     PenaltyYds       Fumbles Interceptions TotalTurnovers
## Differential       0.017601130 -1.442010e-01  -0.347408586   -0.352260285
## NetYards           0.092501983 -9.215913e-05  -0.182840770   -0.135727097
## TurnoverMargin     0.037534837 -4.544647e-01  -0.565898315   -0.717673298
## PassingCmp         0.125427191  1.753247e-02   0.099529068    0.085337798
## PassingAtt         0.119567124  2.747887e-02   0.254940410    0.207169253
## PassingPct         0.055995229 -1.783733e-02  -0.236272865   -0.186999804
## PassingYds         0.151131721  8.811146e-03   0.017618719    0.018846333
## PassingTD          0.100160624 -4.801886e-02  -0.114458545   -0.116391065
## RushingAtt        -0.002199279  2.557860e-02  -0.193975079   -0.127168356
## RushingYds         0.033168959 -2.811840e-02  -0.216449107   -0.179027989
## RushingAvg         0.054284078 -5.826194e-02  -0.172564128   -0.166216652
## RushingTD          0.009108827 -5.870912e-02  -0.233234180   -0.211526460
## OffensivePlays     0.116798125  5.141188e-02   0.070742086    0.086176943
## OffensiveYards     0.147785771 -1.461193e-02  -0.153058437   -0.123142627
## OffenseAvg         0.101590794 -4.910112e-02  -0.220863037   -0.196051667
## FirstDownPass      0.096191798 -2.669702e-03   0.047918056    0.033805622
## FirstDownRush     -0.003811064 -1.275891e-02  -0.182386133   -0.143689431
## FirstDownPen       0.133197652 -1.733341e-04   0.021457525    0.015807775
## FirstDownTotal     0.098139564 -1.052251e-02  -0.091526136   -0.074806518
## Penalties          0.903246349 -5.346654e-03   0.027625989    0.016995007
## PenaltyYds         1.000000000 -1.403761e-02   0.015917475    0.002612761
## Fumbles           -0.014037613  1.000000e+00   0.020686856    0.670582481
## Interceptions      0.015917475  2.068686e-02   1.000000000    0.755548472
## TotalTurnovers     0.002612761  6.705825e-01   0.755548472    1.000000000
## TeamScore          0.081291125 -9.221149e-02  -0.276837519   -0.265831719
## OpponentScore      0.055514238  1.318612e-01   0.261769161    0.280630915
## DefPassingCmp      0.111411452 -3.973445e-02  -0.017382571   -0.038933078
## DefPassingAtt      0.162686876 -3.109202e-02  -0.058249476   -0.063593263
## DefPassingPct     -0.043181735 -2.298935e-02   0.079458063    0.043886543
## DefPassingYds      0.096147185 -3.794686e-02   0.023141664   -0.007693062
## DefPassingTD       0.093042717  3.917292e-02   0.099335433    0.099373662
## DefRushingAtt     -0.059428915  7.073269e-02   0.145548041    0.154342125
## DefRushingYds     -0.086487888  2.161863e-02   0.125655719    0.107400997
## DefRushingAvg     -0.073680859 -9.993266e-03   0.083883084    0.055685410
## DefRushingTD      -0.016742606  7.668263e-02   0.161302037    0.169930092
## DefPlays           0.105229463  3.512879e-02   0.077938067    0.080847102
## DefYards           0.012497218 -1.430737e-02   0.112722764    0.074264925
## DefAvg            -0.043324322 -3.375146e-02   0.094214745    0.047783145
## DefFirstDownPass   0.080096704 -4.961707e-02   0.001262556   -0.031573932
## DefFirstDownRush  -0.095022978  1.225369e-03   0.092104959    0.069144207
## DefFirstDownPen    0.656398393 -1.908304e-02   0.005624566   -0.008330444
## DefFirstDownTotal  0.140738712 -3.865811e-02   0.066245867    0.023823953
## DefPenalties       0.193097182  2.205344e-02   0.053183584    0.053912026
## DefPenaltyYds      0.197512296  2.200282e-02   0.064072314    0.061958232
## DefFumbles         0.016184547  2.463791e-02  -0.012823924    0.006628298
## DefInterceptions   0.061722386 -5.156149e-03  -0.074209524   -0.058441483
## DefTotalTurnovers  0.056446760  1.217256e-02  -0.063555262   -0.039181745
## Season             0.043715876 -7.685922e-02  -0.041631219   -0.081250800
##                      TeamScore OpponentScore DefPassingCmp DefPassingAtt
## Differential       0.781067377  -0.769642620  -0.064738171   0.150488394
## NetYards           0.637250008  -0.631925770  -0.222740348  -0.034761786
## TurnoverMargin     0.377082264  -0.373145513   0.082821892   0.181901022
## PassingCmp         0.183342682   0.138560556   0.083460009   0.075998001
## PassingAtt        -0.035933316   0.272001348   0.083570904   0.057944813
## PassingPct         0.448358095  -0.206697090   0.022060210   0.056923769
## PassingYds         0.431051906   0.090668157   0.126357936   0.145063141
## PassingTD          0.618539629  -0.019512592   0.091773507   0.144169653
## RushingAtt         0.343571991  -0.223024981  -0.044763075   0.073608528
## RushingYds         0.571429522  -0.246049036   0.002351343   0.098937001
## RushingAvg         0.560340983  -0.200498698   0.033307036   0.093487708
## RushingTD          0.698724429  -0.188554772   0.043038468   0.130716692
## OffensivePlays     0.287897620   0.060340486   0.040919681   0.126941028
## OffensiveYards     0.790058468  -0.116896356   0.103943303   0.193714572
## OffenseAvg         0.761055147  -0.183237536   0.094216225   0.150186343
## FirstDownPass      0.348506805   0.078087301   0.091467148   0.099017964
## FirstDownRush      0.492279931  -0.219697357  -0.035195207   0.042537652
## FirstDownPen       0.069696119   0.080156897   0.055082764   0.050446788
## FirstDownTotal     0.632897568  -0.083219329   0.054621111   0.115086837
## Penalties          0.045390014   0.069089389   0.102064433   0.148129510
## PenaltyYds         0.081291125   0.055514238   0.111411452   0.162686876
## Fumbles           -0.092211487   0.131861239  -0.039734445  -0.031092018
## Interceptions     -0.276837519   0.261769161  -0.017382571  -0.058249476
## TotalTurnovers    -0.265831719   0.280630915  -0.038933078  -0.063593263
## TeamScore          1.000000000  -0.202449142   0.110635407   0.235566171
## OpponentScore     -0.202449142   1.000000000   0.214646894   0.004853732
## DefPassingCmp      0.110635407   0.214646894   1.000000000   0.888534051
## DefPassingAtt      0.235566171   0.004853732   0.888534051   1.000000000
## DefPassingPct     -0.205209988   0.449588246   0.527936650   0.124019463
## DefPassingYds      0.056396074   0.461238083   0.811002597   0.696116964
## DefPassingTD      -0.026902967   0.630074932   0.431985918   0.288984139
## DefRushingAtt     -0.220249045   0.346909797  -0.357667664  -0.457042860
## DefRushingYds     -0.246450675   0.568876938  -0.303784505  -0.424394812
## DefRushingAvg     -0.202890701   0.555199375  -0.170640401  -0.274715155
## DefRushingTD      -0.184304923   0.692177201  -0.107643356  -0.260693452
## DefPlays           0.027517830   0.327538771   0.543938457   0.561465097
## DefYards          -0.139273423   0.796847454   0.424314893   0.241629847
## DefAvg            -0.199723885   0.766161290   0.189980837  -0.036500573
## DefFirstDownPass   0.040803814   0.382180089   0.858417270   0.750367056
## DefFirstDownRush  -0.221952586   0.492314907  -0.220058651  -0.338567902
## DefFirstDownPen    0.060041899   0.094446672   0.166792838   0.202250647
## DefFirstDownTotal -0.112838954   0.648164723   0.507510150   0.352847040
## DefPenalties       0.066777296   0.047608838   0.129228123   0.138563162
## DefPenaltyYds      0.045061806   0.091400033   0.124944592   0.119897735
## DefFumbles         0.141183882  -0.091979574   0.015863025   0.025781372
## DefInterceptions   0.249951833  -0.265625593   0.094022164   0.243583489
## DefTotalTurnovers  0.277739467  -0.257430498   0.080273452   0.198013119
## Season             0.006049668   0.011888084  -0.028328659  -0.041701025
##                   DefPassingPct DefPassingYds DefPassingTD DefRushingAtt
## Differential       -0.420462531  -0.257339941  -0.41930782 -0.3648042744
## NetYards           -0.422176950  -0.397669138  -0.38051554 -0.4156719928
## TurnoverMargin     -0.154782085   0.017015633  -0.14799556 -0.1927488957
## PassingCmp          0.036945250   0.127150934   0.11207117 -0.0356416142
## PassingAtt          0.077374243   0.156497317   0.17106759  0.0839936289
## PassingPct         -0.073379047  -0.021966011  -0.08316878 -0.2138003701
## PassingYds         -0.002052903   0.155256065   0.09798277 -0.0370889603
## PassingTD          -0.081413409   0.075376864   0.03505334 -0.0510535147
## RushingAtt         -0.216287969  -0.050233964  -0.05901043 -0.4102166420
## RushingYds         -0.180720848  -0.030415762  -0.07850262 -0.2765693874
## RushingAvg         -0.115717537  -0.010078082  -0.07078651 -0.1176949379
## RushingTD          -0.152791861   0.005118324  -0.04470253 -0.1962423099
## OffensivePlays     -0.126835921   0.108267515   0.11448597 -0.3028923478
## OffensiveYards     -0.141363954   0.101973122   0.01851589 -0.2437429725
## OffenseAvg         -0.096310447   0.048186399  -0.05340694 -0.1082911321
## FirstDownPass       0.008201755   0.125262682   0.09058653 -0.0788586132
## FirstDownRush      -0.156338912  -0.053026691  -0.07241421 -0.3153770802
## FirstDownPen        0.036124617   0.085484505   0.08190039 -0.0437639450
## FirstDownTotal     -0.098512229   0.073302813   0.03341693 -0.2999595083
## Penalties          -0.036848531   0.096286575   0.08994249 -0.0453869976
## PenaltyYds         -0.043181735   0.096147185   0.09304272 -0.0594289149
## Fumbles            -0.022989345  -0.037946859   0.03917292  0.0707326851
## Interceptions       0.079458063   0.023141664   0.09933543  0.1455480406
## TotalTurnovers      0.043886543  -0.007693062   0.09937366  0.1543421251
## TeamScore          -0.205209988   0.056396074  -0.02690297 -0.2202490448
## OpponentScore       0.449588246   0.461238083   0.63007493  0.3469097966
## DefPassingCmp       0.527936650   0.811002597   0.43198592 -0.3576676643
## DefPassingAtt       0.124019463   0.696116964   0.28898414 -0.4570428600
## DefPassingPct       1.000000000   0.489075819   0.39650239  0.0334096923
## DefPassingYds       0.489075819   1.000000000   0.63385166 -0.2418870888
## DefPassingTD        0.396502392   0.633851663   1.00000000 -0.0473965023
## DefRushingAtt       0.033409692  -0.241887089  -0.04739650  1.0000000000
## DefRushingYds       0.102635384  -0.172013159   0.07771343  0.7391873224
## DefRushingAvg       0.133036964  -0.057509274   0.15729694  0.3720422494
## DefRushingTD        0.238808298   0.038341710  -0.01416026  0.4883122699
## DefPlays            0.153529419   0.461801976   0.24103860  0.4794022253
## DefYards            0.469912225   0.674929292   0.56768532  0.3592633482
## DefAvg              0.483874653   0.534876301   0.53421323  0.1519570904
## DefFirstDownPass    0.485967332   0.888603335   0.53272207 -0.2149967952
## DefFirstDownRush    0.123910001  -0.129646601   0.08022841  0.7888528350
## DefFirstDownPen     0.004410449   0.141000183   0.11566582 -0.0002455711
## DefFirstDownTotal   0.442541414   0.587380037   0.47044073  0.4033934413
## DefPenalties        0.034579594   0.147205592   0.08036485 -0.0238558553
## DefPenaltyYds       0.058957963   0.152557145   0.10315158  0.0025346468
## DefFumbles         -0.018162723   0.007005965  -0.05021171  0.0263769198
## DefInterceptions   -0.224175953   0.016451788  -0.10924136 -0.1892407555
## DefTotalTurnovers  -0.178623380   0.016794868  -0.11391813 -0.1236824864
## Season              0.017373437  -0.003226989   0.01101258 -0.0065777142
##                   DefRushingYds DefRushingAvg DefRushingTD      DefPlays
## Differential       -0.523424607 -0.4863031759 -0.561529600 -0.1909143856
## NetYards           -0.547819825 -0.4871370004 -0.464507699 -0.4210217236
## TurnoverMargin     -0.194212799 -0.1469244778 -0.258439430  0.0001525553
## PassingCmp          0.018647173  0.0490502813  0.061945922  0.0418261399
## PassingAtt          0.119747148  0.1144628084  0.155716440  0.1353168586
## PassingPct         -0.179479743 -0.1150532210 -0.155117094 -0.1427705801
## PassingYds         -0.010300250  0.0086495098  0.028151375  0.1086246317
## PassingTD          -0.071383520 -0.0656727117 -0.033926688  0.0947510369
## RushingAtt         -0.279183263 -0.1216210521 -0.194448775 -0.3090197221
## RushingYds         -0.225077345 -0.1341365822 -0.192176011 -0.1596891208
## RushingAvg         -0.131739440 -0.1081341745 -0.145311374 -0.0172559779
## RushingTD          -0.196349300 -0.1511653556 -0.156635569 -0.0536000054
## OffensivePlays     -0.143922887 -0.0007670721 -0.028349305 -0.1565479001
## OffensiveYards     -0.182292260 -0.0966878468 -0.125784441 -0.0356339359
## OffenseAvg         -0.134492281 -0.1185107448 -0.138422906  0.0474361958
## FirstDownPass      -0.026930969  0.0118692816  0.018320394  0.0243322208
## FirstDownRush      -0.219647488 -0.1024397880 -0.169169555 -0.2514420854
## FirstDownPen        0.004971625  0.0402209526  0.029630574  0.0090586645
## FirstDownTotal     -0.181281160 -0.0592662502 -0.103644138 -0.1655155810
## Penalties          -0.069403770 -0.0597464352  0.001729374  0.1039300196
## PenaltyYds         -0.086487888 -0.0736808591 -0.016742606  0.1052294630
## Fumbles             0.021618628 -0.0099932661  0.076682629  0.0351287926
## Interceptions       0.125655719  0.0838830841  0.161302037  0.0779380669
## TotalTurnovers      0.107400997  0.0556854104  0.169930092  0.0808471024
## TeamScore          -0.246450675 -0.2028907014 -0.184304923  0.0275178301
## OpponentScore       0.568876938  0.5551993748  0.692177201  0.3275387714
## DefPassingCmp      -0.303784505 -0.1706404012 -0.107643356  0.5439384572
## DefPassingAtt      -0.424394812 -0.2747151550 -0.260693452  0.5614650973
## DefPassingPct       0.102635384  0.1330369637  0.238808298  0.1535294189
## DefPassingYds      -0.172013159 -0.0575092741  0.038341710  0.4618019756
## DefPassingTD        0.077713426  0.1572969436 -0.014160258  0.2410385975
## DefRushingAtt       0.739187322  0.3720422494  0.488312270  0.4794022253
## DefRushingYds       1.000000000  0.8730947621  0.688245075  0.2689666214
## DefRushingAvg       0.873094762  1.0000000000  0.600041582  0.0750924781
## DefRushingTD        0.688245075  0.6000415822  1.000000000  0.1970839405
## DefPlays            0.268966621  0.0750924781  0.197083940  1.0000000000
## DefYards            0.610787296  0.6079029094  0.546346178  0.5726537077
## DefAvg              0.579906813  0.7047277389  0.543402451  0.1054439997
## DefFirstDownPass   -0.165502747 -0.0636257511  0.025657171  0.5403468891
## DefFirstDownRush    0.868314472  0.6624669099  0.587340983  0.3998567473
## DefFirstDownPen    -0.055707347 -0.0663814432  0.015665968  0.1993277518
## DefFirstDownTotal   0.480393124  0.4048150894  0.437620119  0.7234459497
## DefPenalties       -0.002806677  0.0189733608 -0.021067247  0.1145227495
## DefPenaltyYds       0.039258125  0.0602355258  0.018572174  0.1206585558
## DefFumbles         -0.026783262 -0.0547759457 -0.054120831  0.0499778396
## DefInterceptions   -0.208131868 -0.1613333457 -0.224866874  0.0642770948
## DefTotalTurnovers  -0.172283106 -0.1556512003 -0.202500002  0.0803063695
## Season              0.015352689  0.0291418446  0.016225977 -0.0472650922
##                       DefYards       DefAvg DefFirstDownPass DefFirstDownRush
## Differential      -0.598913227 -0.618758489     -0.217094325     -0.458632617
## NetYards          -0.729979536 -0.639567669     -0.365830735     -0.513799549
## TurnoverMargin    -0.131797812 -0.161574293      0.042586183     -0.144228503
## PassingCmp         0.116168390  0.108788890      0.091233051     -0.019627052
## PassingAtt         0.215484942  0.175755717      0.109208886      0.062313958
## PassingPct        -0.152112461 -0.107046906     -0.011191012     -0.154341585
## PassingYds         0.117075612  0.066058087      0.123142671     -0.034360788
## PassingTD          0.007116432 -0.058840155      0.065395375     -0.068080474
## RushingAtt        -0.249498265 -0.119690358     -0.090092408     -0.317355086
## RushingYds        -0.193040997 -0.146487656     -0.047490894     -0.220166727
## RushingAvg        -0.106779574 -0.127188735     -0.008586427     -0.100294586
## RushingTD         -0.142960915 -0.152049693     -0.007229665     -0.173767081
## OffensivePlays    -0.020782288  0.061986249      0.023710984     -0.236976322
## OffensiveYards    -0.054582037 -0.059835995      0.062820458     -0.197943110
## OffenseAvg        -0.062010033 -0.115152176      0.053558602     -0.096233511
## FirstDownPass      0.080510479  0.073494860      0.094812163     -0.048360863
## FirstDownRush     -0.207147883 -0.107747588     -0.068467329     -0.224658105
## FirstDownPen       0.072434313  0.081364281      0.065042818     -0.016408982
## FirstDownTotal    -0.076869161 -0.006762158      0.030148892     -0.213167195
## Penalties          0.025406067 -0.026690341      0.078466818     -0.080014867
## PenaltyYds         0.012497218 -0.043324322      0.080096704     -0.095022978
## Fumbles           -0.014307373 -0.033751463     -0.049617071      0.001225369
## Interceptions      0.112722764  0.094214745      0.001262556      0.092104959
## TotalTurnovers     0.074264925  0.047783145     -0.031573932      0.069144207
## TeamScore         -0.139273423 -0.199723885      0.040803814     -0.221952586
## OpponentScore      0.796847454  0.766161290      0.382180089      0.492314907
## DefPassingCmp      0.424314893  0.189980837      0.858417270     -0.220058651
## DefPassingAtt      0.241629847 -0.036500573      0.750367056     -0.338567902
## DefPassingPct      0.469912225  0.483874653      0.485967332      0.123910001
## DefPassingYds      0.674929292  0.534876301      0.888603335     -0.129646601
## DefPassingTD       0.567685318  0.534213234      0.532722072      0.080228407
## DefRushingAtt      0.359263348  0.151957090     -0.214996795      0.788852835
## DefRushingYds      0.610787296  0.579906813     -0.165502747      0.868314472
## DefRushingAvg      0.607902909  0.704727739     -0.063625751      0.662466910
## DefRushingTD       0.546346178  0.543402451      0.025657171      0.587340983
## DefPlays           0.572653708  0.105444000      0.540346889      0.399856747
## DefYards           1.000000000  0.864462231      0.590268014      0.546201809
## DefAvg             0.864462231  1.000000000      0.390009234      0.423536375
## DefFirstDownPass   0.590268014  0.390009234      1.000000000     -0.141850255
## DefFirstDownRush   0.546201809  0.423536375     -0.141850255      1.000000000
## DefFirstDownPen    0.071605026 -0.025614875      0.137431352     -0.052058450
## DefFirstDownTotal  0.831958681  0.576278354      0.653641009      0.584664115
## DefPenalties       0.116217881  0.068228282      0.091887049     -0.035947615
## DefPenaltyYds      0.152027850  0.109505111      0.099033975      0.001989852
## DefFumbles        -0.014430707 -0.047710501     -0.002813518     -0.011352217
## DefInterceptions  -0.142677056 -0.206269402      0.042542473     -0.176151476
## DefTotalTurnovers -0.115548882 -0.184499527      0.029829434     -0.138458223
## Season             0.008906115  0.041294557     -0.019898843      0.009579210
##                   DefFirstDownPen DefFirstDownTotal DefPenalties DefPenaltyYds
## Differential        -0.0210781403      -0.486870948  0.013179353  -0.028902103
## NetYards            -0.0095468986      -0.632925216 -0.064521305  -0.101133844
## TurnoverMargin       0.0146372877      -0.066460751 -0.030278199  -0.046192301
## PassingCmp           0.0516278342       0.064255648  0.097721027   0.108066606
## PassingAtt           0.0493365901       0.134090419  0.144271935   0.162654164
## PassingPct           0.0269159393      -0.110256110 -0.043012134  -0.053905077
## PassingYds           0.0785769921       0.083106670  0.092139354   0.091809187
## PassingTD            0.0726270069       0.016190934  0.087539127   0.087458617
## RushingAtt          -0.0473819882      -0.301942200 -0.044234601  -0.060368138
## RushingYds          -0.0064690578      -0.194065174 -0.066155832  -0.088133097
## RushingAvg           0.0267430155      -0.073946954 -0.057171981  -0.076423381
## RushingTD            0.0116282754      -0.126211617  0.001478081  -0.023191416
## OffensivePlays       0.0044182172      -0.151100644  0.101764432   0.104842750
## OffensiveYards       0.0585079679      -0.082828263  0.023336190   0.006082620
## OffenseAvg           0.0648182595      -0.015662267 -0.029252587  -0.051699931
## FirstDownPass        0.0594882546       0.043655644  0.074673629   0.076942358
## FirstDownRush       -0.0271049617      -0.224352618 -0.077513273  -0.097695640
## FirstDownPen         0.0709464960       0.046460027  0.542175075   0.658548102
## FirstDownTotal       0.0348967103      -0.123036459  0.124255326   0.137953942
## Penalties            0.5448156356       0.124940137  0.190344623   0.193217609
## PenaltyYds           0.6563983927       0.140738712  0.193097182   0.197512296
## Fumbles             -0.0190830400      -0.038658110  0.022053436   0.022002823
## Interceptions        0.0056245655       0.066245867  0.053183584   0.064072314
## TotalTurnovers      -0.0083304443       0.023823953  0.053912026   0.061958232
## TeamScore            0.0600418989      -0.112838954  0.066777296   0.045061806
## OpponentScore        0.0944466717       0.648164723  0.047608838   0.091400033
## DefPassingCmp        0.1667928379       0.507510150  0.129228123   0.124944592
## DefPassingAtt        0.2022506473       0.352847040  0.138563162   0.119897735
## DefPassingPct        0.0044104488       0.442541414  0.034579594   0.058957963
## DefPassingYds        0.1410001827       0.587380037  0.147205592   0.152557145
## DefPassingTD         0.1156658207       0.470440732  0.080364847   0.103151581
## DefRushingAtt       -0.0002455711       0.403393441 -0.023855855   0.002534647
## DefRushingYds       -0.0557073473       0.480393124 -0.002806677   0.039258125
## DefRushingAvg       -0.0663814432       0.404815089  0.018973361   0.060235526
## DefRushingTD         0.0156659684       0.437620119 -0.021067247   0.018572174
## DefPlays             0.1993277518       0.723445950  0.114522749   0.120658556
## DefYards             0.0716050265       0.831958681  0.116217881   0.152027850
## DefAvg              -0.0256148747       0.576278354  0.068228282   0.109505111
## DefFirstDownPass     0.1374313523       0.653641009  0.091887049   0.099033975
## DefFirstDownRush    -0.0520584497       0.584664115 -0.035947615   0.001989852
## DefFirstDownPen      1.0000000000       0.282939522  0.131267111   0.134211435
## DefFirstDownTotal    0.2829395221       1.000000000  0.070161291   0.103058264
## DefPenalties         0.1312671113       0.070161291  1.000000000   0.900744066
## DefPenaltyYds        0.1342114354       0.103058264  0.900744066   1.000000000
## DefFumbles          -0.0026003776      -0.010026151 -0.008397144  -0.017131676
## DefInterceptions     0.0194055745      -0.087683835  0.020716236   0.008367985
## DefTotalTurnovers    0.0127507987      -0.071764094  0.009959436  -0.004905025
## Season               0.0678208894       0.005517816  0.027121670   0.041720288
##                      DefFumbles DefInterceptions DefTotalTurnovers       Season
## Differential       0.1506992798     0.3323388335       0.345230083 -0.003636210
## NetYards           0.0016894054     0.1665064148       0.125002132 -0.001569119
## TurnoverMargin     0.4611567538     0.5702003054       0.723964894 -0.002887603
## PassingCmp        -0.0409238359    -0.0287094744      -0.047955818 -0.030911733
## PassingAtt        -0.0352683058    -0.0673938145      -0.073067543 -0.042815333
## PassingPct        -0.0177987463     0.0688612134       0.039676760  0.011534916
## PassingYds        -0.0375733487     0.0086121204      -0.018006148 -0.006117554
## PassingTD          0.0434153059     0.0883846599       0.093981546  0.007749168
## RushingAtt         0.0710373911     0.1432153386       0.152731898 -0.006470762
## RushingYds         0.0235907609     0.1189308042       0.103830416  0.015090607
## RushingAvg        -0.0069041024     0.0763947673       0.052362318  0.029310251
## RushingTD          0.0819343368     0.1535987879       0.167539382  0.010761615
## OffensivePlays     0.0318497808     0.0678983530       0.071221668 -0.048660609
## OffensiveYards    -0.0121339680     0.0988848301       0.065699798  0.006719496
## OffenseAvg        -0.0285341525     0.0801805815       0.041124510  0.038470215
## FirstDownPass     -0.0485113283    -0.0127221493      -0.040989258 -0.021594636
## FirstDownRush      0.0007492654     0.0855201980       0.064126014  0.008718165
## FirstDownPen      -0.0219681886    -0.0006859365      -0.014785143  0.066242195
## FirstDownTotal    -0.0394374483     0.0518375280       0.012948409  0.003573008
## Penalties          0.0175079007     0.0547373404       0.052108799  0.029358706
## PenaltyYds         0.0161845471     0.0617223857       0.056446760  0.043715876
## Fumbles            0.0246379075    -0.0051561488       0.012172560 -0.076859221
## Interceptions     -0.0128239235    -0.0742095243      -0.063555262 -0.041631219
## TotalTurnovers     0.0066282979    -0.0584414828      -0.039181745 -0.081250800
## TeamScore          0.1411838824     0.2499518329       0.277739467  0.006049668
## OpponentScore     -0.0919795740    -0.2656255930      -0.257430498  0.011888084
## DefPassingCmp      0.0158630249     0.0940221643       0.080273452 -0.028328659
## DefPassingAtt      0.0257813722     0.2435834885       0.198013119 -0.041701025
## DefPassingPct     -0.0181627225    -0.2241759530      -0.178623380  0.017373437
## DefPassingYds      0.0070059647     0.0164517885       0.016794868 -0.003226989
## DefPassingTD      -0.0502117148    -0.1092413599      -0.113918126  0.011012582
## DefRushingAtt      0.0263769198    -0.1892407555      -0.123682486 -0.006577714
## DefRushingYds     -0.0267832623    -0.2081318682      -0.172283106  0.015352689
## DefRushingAvg     -0.0547759457    -0.1613333457      -0.155651200  0.029141845
## DefRushingTD      -0.0541208313    -0.2248668737      -0.202500002  0.016225977
## DefPlays           0.0499778396     0.0642770948       0.080306370 -0.047265092
## DefYards          -0.0144307070    -0.1426770564      -0.115548882  0.008906115
## DefAvg            -0.0477105007    -0.2062694023      -0.184499527  0.041294557
## DefFirstDownPass  -0.0028135177     0.0425424733       0.029829434 -0.019898843
## DefFirstDownRush  -0.0113522169    -0.1761514759      -0.138458223  0.009579210
## DefFirstDownPen   -0.0026003776     0.0194055745       0.012750799  0.067820889
## DefFirstDownTotal -0.0100261507    -0.0876838353      -0.071764094  0.005517816
## DefPenalties      -0.0083971436     0.0207162360       0.009959436  0.027121670
## DefPenaltyYds     -0.0171316758     0.0083679848      -0.004905025  0.041720288
## DefFumbles         1.0000000000     0.0248441007       0.668277532 -0.077380805
## DefInterceptions   0.0248441007     1.0000000000       0.760285188 -0.046159898
## DefTotalTurnovers  0.6682775322     0.7602851879       1.000000000 -0.084630780
## Season            -0.0773808053    -0.0461598980      -0.084630780  1.000000000</code></pre>
<p>Notice right away – NetYards is highly correlated. But NetYards’s also highly correlated with RushingYards, OffensiveYards and DefYards. And that makes sense: those things all feed into NetYards. Including all of these measures would be pointless – they would add error without adding much in the way of predictive power.</p>
<blockquote>
<p><strong>Your turn</strong>: What else do you see? What other values have predictive power and aren’t co-correlated?</p>
</blockquote>
<p>We can add more just by simply adding them. Let’s add the average yard per play for both offense and defense. They’re correlated to NetYards, but not as much as you might expect.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="multiple-regression.html#cb126-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Differential <span class="sc">~</span> NetYards <span class="sc">+</span> TurnoverMargin <span class="sc">+</span> DefAvg <span class="sc">+</span> OffenseAvg, <span class="at">data=</span>logs)</span>
<span id="cb126-2"><a href="multiple-regression.html#cb126-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Differential ~ NetYards + TurnoverMargin + DefAvg + 
##     OffenseAvg, data = logs)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -38.254  -6.255  -0.002   6.229  37.507 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     0.4960303  0.4292118   1.156    0.248    
## NetYards        0.0547465  0.0008007  68.376   &lt;2e-16 ***
## TurnoverMargin  3.8806793  0.0410484  94.539   &lt;2e-16 ***
## DefAvg         -3.9374905  0.0738754 -53.299   &lt;2e-16 ***
## OffenseAvg      3.9152803  0.0729586  53.664   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.45 on 15601 degrees of freedom
##   (1 observation deleted due to missingness)
## Multiple R-squared:  0.8287, Adjusted R-squared:  0.8287 
## F-statistic: 1.887e+04 on 4 and 15601 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Go down the list:</p>
<p>What is the Adjusted R-squared now?
What is the p-value and is it less than .05?
What is the Residual standard error?</p>
<p>The final thing we can do with this is predict things. Look at our coefficients table. See the Estimates? We can build a formula from that, same as we did with linear regressions.</p>
<p>How does this apply in the real world? Let’s pretend for a minute that you are Scott Frost, and you have a mess on your hands. Your job is to win conference titles. To do that, we need to know what attributes of a team should we emphasize. We can do that by looking at what previous Big Ten conference champions looked like.</p>
<p>So if our goal is to predict a conference champion team, we need to know what those teams did. Here’s the regular season conference champions in this dataset.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="multiple-regression.html#cb128-1" aria-hidden="true" tabindex="-1"></a>logs <span class="sc">%&gt;%</span> </span>
<span id="cb128-2"><a href="multiple-regression.html#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Team <span class="sc">==</span> <span class="st">&quot;Ohio State&quot;</span> <span class="sc">&amp;</span> Season <span class="sc">==</span> <span class="dv">2020</span> <span class="sc">|</span> Team <span class="sc">==</span> <span class="st">&quot;Ohio State&quot;</span> <span class="sc">&amp;</span> Season <span class="sc">==</span> <span class="dv">2019</span> <span class="sc">|</span> Team <span class="sc">==</span> <span class="st">&quot;Ohio State&quot;</span> <span class="sc">&amp;</span> Season <span class="sc">==</span> <span class="dv">2018</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb128-3"><a href="multiple-regression.html#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb128-4"><a href="multiple-regression.html#cb128-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">meanNetYards =</span> <span class="fu">mean</span>(NetYards),</span>
<span id="cb128-5"><a href="multiple-regression.html#cb128-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">meanTurnoverMargin =</span> <span class="fu">mean</span>(TurnoverMargin),</span>
<span id="cb128-6"><a href="multiple-regression.html#cb128-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">meanDefAvg =</span> <span class="fu">mean</span>(DefAvg),</span>
<span id="cb128-7"><a href="multiple-regression.html#cb128-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">meanOffenseAvg =</span> <span class="fu">mean</span>(OffenseAvg)</span>
<span id="cb128-8"><a href="multiple-regression.html#cb128-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   meanNetYards meanTurnoverMargin meanDefAvg meanOffenseAvg
##          &lt;dbl&gt;              &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;
## 1         196.              0.676       5.04           6.91</code></pre>
<p>Now it’s just plug and chug.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="multiple-regression.html#cb130-1" aria-hidden="true" tabindex="-1"></a>(<span class="fl">0.0547465</span><span class="sc">*</span><span class="fl">195.8824</span>) <span class="sc">+</span> (<span class="fl">3.8806793</span><span class="sc">*</span><span class="fl">0.6764706</span>) <span class="sc">+</span> (<span class="sc">-</span><span class="fl">3.9374905</span><span class="sc">*</span><span class="fl">5.044118</span> ) <span class="sc">+</span> (<span class="fl">3.9152803</span><span class="sc">*</span><span class="fl">6.908824</span>) <span class="sc">+</span> <span class="fl">0.4960303</span></span></code></pre></div>
<pre><code>## [1] 21.03389</code></pre>
<p>So a team with those numbers is going to average scoring 21 more points per game than their opponent. Sound like Ohio State in the last three years?</p>
<p>How does that compare to Nebraska this season?</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="multiple-regression.html#cb132-1" aria-hidden="true" tabindex="-1"></a>logs <span class="sc">%&gt;%</span> </span>
<span id="cb132-2"><a href="multiple-regression.html#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb132-3"><a href="multiple-regression.html#cb132-3" aria-hidden="true" tabindex="-1"></a>    Team <span class="sc">==</span> <span class="st">&quot;Nebraska&quot;</span> <span class="sc">&amp;</span> Season <span class="sc">==</span> <span class="dv">2020</span></span>
<span id="cb132-4"><a href="multiple-regression.html#cb132-4" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb132-5"><a href="multiple-regression.html#cb132-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb132-6"><a href="multiple-regression.html#cb132-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">meanNetYards =</span> <span class="fu">mean</span>(NetYards),</span>
<span id="cb132-7"><a href="multiple-regression.html#cb132-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">meanTurnoverMargin =</span> <span class="fu">mean</span>(TurnoverMargin),</span>
<span id="cb132-8"><a href="multiple-regression.html#cb132-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">meanDefAvg =</span> <span class="fu">mean</span>(DefAvg),</span>
<span id="cb132-9"><a href="multiple-regression.html#cb132-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">meanOffenseAvg =</span> <span class="fu">mean</span>(OffenseAvg)</span>
<span id="cb132-10"><a href="multiple-regression.html#cb132-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   meanNetYards meanTurnoverMargin meanDefAvg meanOffenseAvg
##          &lt;dbl&gt;              &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;
## 1            5              -1.38       5.44           5.54</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="multiple-regression.html#cb134-1" aria-hidden="true" tabindex="-1"></a>(<span class="fl">0.0547465</span><span class="sc">*</span><span class="dv">5</span>) <span class="sc">+</span> (<span class="fl">3.8806793</span><span class="sc">*-</span><span class="fl">1.375</span>) <span class="sc">+</span> (<span class="sc">-</span><span class="fl">3.9374905</span><span class="sc">*</span><span class="fl">5.4375</span>) <span class="sc">+</span> (<span class="fl">3.9152803</span><span class="sc">*</span><span class="fl">5.5375</span>) <span class="sc">+</span> <span class="fl">0.4960303</span></span></code></pre></div>
<pre><code>## [1] -4.295411</code></pre>
<p>By this model, it predicted we would average being outscored by our opponents by 4.3 points over the season. Reality? We were outscored by 6.25 on average.</p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="correlations-and-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="residuals.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["SportsData.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
